var data = 
[
//================================================================================================
// rarity Material: 小怪，素材
//================================================================================================
	{
		"name": "瘋頭", "id": "00", "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 1, 0, 1, 1, 0 ],
						  [ 1, 0, 0, 0, 0 ],
						  [ 1, 0, 0, 0, 0 ],
						  [ 1, 0, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "人面鳥", "id": "+", "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 0, 0, 1, 0, 0 ],
						  [ 0, 0, 1, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "升級素材", "id": 0, "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 1, 1, 1, 0, 0 ],
						  [ 1, 0, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "經驗素材", "id": 1, "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 0, 0, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "進化元素", "id": 2, "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 0, 1 ],
						  [ 1, 1, 1, 0, 1 ],
						  [ 1, 1, 1, 0, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "進化素材", "id": 3, "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 0, 1, 1 ],
						  [ 0, 1, 0, 1, 1 ],
						  [ 0, 1, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "解放素材", "id": 4, "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 0, 0, 0, 1, 1 ],
						  [ 0, 0, 0, 1, 1 ],
						  [ 0, 0, 0, 1, 1 ],
						  [ 0, 0, 0, 0, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "地精", "id": 5, "trDisplay": false, "label": true, "rarity": "Material", "type": "Spirit",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "妖精", "id": 6, "trDisplay": false, "label": true, "rarity": "Material", "type": "Spirit",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "蜥蜴", "id": 7, "trDisplay": false, "label": true, "rarity": "Material", "type": "Dragon",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "小魔女", "id": 8, "trDisplay": false, "label": true, "rarity": "Material", "type": "Human",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "史萊姆", "id": 9, "trDisplay": false, "label": true, "rarity": "Material", "type": "Spirit",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "狼人", "id": 10, "trDisplay": false, "label": true, "rarity": "Material", "type": "Beast",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "星宮石像", "id": 11, "trDisplay": false, "label": true, "rarity": "Material", "type": "Material",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "希臘妖獸", "id": 12, "trDisplay": false, "label": true, "rarity": "Material", "type": "Beast",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "夥伴鴨", "id": 13, "trDisplay": false, "label": true, "rarity": "Material", "type": "Beast",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "龍牙棋", "id": 14, "trDisplay": false, "label": true, "rarity": "Material", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "萬聖節", "id": 15, "trDisplay": false, "label": true, "rarity": "Material", "type": "Beast",
		"maxLv" : 		[ [ 1, 1, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "修道妖", "id": 16, "trDisplay": false, "label": true, "rarity": "Material", "type": "Spirit",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "異神使徒", "id": 17, "trDisplay": false, "label": true, "rarity": "Material", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "樂團", "id": 18, "trDisplay": false, "label": true, "rarity": "Material", "type": "Human",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "要塞兵", "id": 19, "trDisplay": false, "label": true, "rarity": "Material", "type": "Human",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "小百鬼", "id": 20, "trDisplay": false, "label": true, "rarity": "Material", "type": "Spirit",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "軒轅仙獸", "id": 21, "trDisplay": false, "label": true, "rarity": "Material", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "神族守衛", "id": 22, "trDisplay": false, "label": true, "rarity": "Material", "type": "God",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "鐵皮部隊", "id": 23, "trDisplay": false, "label": true, "rarity": "Material", "type": "Spirit",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "仙劍靈獸", "id": 24, "trDisplay": false, "label": true, "rarity": "Material", "type": "Beast",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "笨小魔", "id": 25, "trDisplay": false, "label": true, "rarity": "Material", "type": "Devil",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "傳教士", "id": 26, "trDisplay": false, "label": true, "rarity": "Material", "type": "Human",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "迪士尼嘍囉", "id": 27, "trDisplay": false, "label": true, "rarity": "Material", "type": "Spirit",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ],
						  [ 0, 0, 0, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "豐腴珍獸", "id": 28, "trDisplay": false, "label": true, "rarity": "Material", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "寧芙", "id": 29, "trDisplay": false, "label": true, "rarity": "Material", "type": "God",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "魔幼龍", "id": 30, "trDisplay": false, "label": true, "rarity": "Material", "type": "Dragon",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},

//================================================================================================
// rarity Normal: 雙周副本，友抽等非石抽
//================================================================================================
	{
		"name": "主角", "id": 1, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Human",
		"maxLv" : 		[ [ 7, 6, 6, 6, 6 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "命運女神", "id": 2, "trDisplay": false, "label": true, "rarity": "Normal", "type": "God",
		"maxLv" : 		[ [ 5, 5, 5, 5, 5 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "中國獸", "id": 3, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Beast",
		"maxLv" : 		[ [ 5, 5, 5, 5, 5 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "遊俠",	"id": 4, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Human",
		"maxLv" : 		[ [ 4, 4, 4, 4, 4 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "防龍",	"id": 5, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Dragon",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "機械獸",	"id": 6, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Beast",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "機龍",	"id": 7, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Dragon",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "傭兵團",	"id": 8, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Devil",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "七原罪",	"id": 9, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 0 ],
						  [ 1, 0, 0, 0, 0 ],
						  [ 1, 0, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "歌姬",	"id": 10, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "遊俠鴨",	"id": 11, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Beast",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "聖誕妖精",	"id": 12, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Spirit",
		"maxLv" : 		[ [ 1, 1, 1, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "魔鏡住民",	"id": 13, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "遠古恐懼",	"id": 14, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "BigBang",	"id": 15, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Human",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "機伴",	"id": 16, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "式神",	"id": 17, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Devil",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "百鬼妖魅",	"id": 18, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "軒轅列傳",	"id": 19, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "巴比倫神",	"id": 20, "trDisplay": false, "label": true, "rarity": "Normal", "type": "God",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "怪物彈珠",	"id": 21, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "童話仙蹤",	"id": 22, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "仙劍列傳",	"id": 23, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 0, 1, 1, 0, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "巨人",	"id": 24, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Human",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "碎羽墜落者",	"id": 25, "trDisplay": false, "label": true, "rarity": "Normal", "type": "God",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "迪士尼惡棍",	"id": 26, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 0, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "列王之爭",	"id": 27, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Human",
		"maxLv" : 		[ [ 0, 0, 0, 0, 1 ],
						  [ 0, 0, 0, 0, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "死亡騎士",	"id": 28, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Devil",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "魔變兇龍",	"id": 29, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "都市傳說",	"id": 30, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "亂入",	"id": 0, "trDisplay": false, "label": true, "rarity": "Normal", "type": "Other",
		"maxLv" : 		[ [ 0, 1, 0, 2, 1 ],
						  [ 0, 1, 0, 1, 1 ],
						  [ 0, 1, 0, 1, 1 ],
						  [ 0, 1, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},


//================================================================================================
// rarity Special: 石抽系列
//================================================================================================
	{
		"name": "北歐神", "id": 1, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 5, 5, 5, 5, 5 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "希臘神", "id": 2, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "埃及神", "id": 3, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "西遊神", "id": 4, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 5, 5, 5, 5, 5 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "西方獸", "id": 5, "trDisplay": true, "label": true, "rarity": "Special", "type": "Beast",
		"maxLv" : 		[ [ 4, 4, 4, 4, 4 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "妖女",	"id": 6, "trDisplay": true, "label": true, "rarity": "Special", "type": "Spirit",
		"maxLv" : 		[ [ 4, 4, 4, 4, 4 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "異界龍", "id": 7, "trDisplay": true, "label": true, "rarity": "Special", "type": "Dragon",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "巫女", "id": 8, "trDisplay": true, "label": true, "rarity": "Special", "type": "Human",
		"maxLv" : 		[ [ 3, 3, 3, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "十二宮", "id": 9, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ],
						  [ 3, 3, 3, 3, 3 ],
						  [ 0, 0, 0, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "不死魔", "id": 10, "trDisplay": true, "label": true, "rarity": "Special", "type": "Devil",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "龍使", "id": 11, "trDisplay": true, "label": true, "rarity": "Special", "type": "Dragon",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "狂魔", "id": 12, "trDisplay": true, "label": true, "rarity": "Special", "type": "Devil",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "遠洋鴨", "id": 13, "trDisplay": true, "label": true, "rarity": "Special", "type": "Beast",
		"maxLv" : 		[ [ 2, 2, 2, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "靈犬", "id": 14, "trDisplay": true, "label": true, "rarity": "Special", "type": "Beast",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "封神", "id": 15, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "迪士尼", "id": 16, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ],
						  [ 0, 0, 0, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "機偶", "id": 17, "trDisplay": true, "label": true, "rarity": "Special", "type": "Human",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "精獸", "id": 18, "trDisplay": true, "label": true, "rarity": "Special", "type": "Beast",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "百鬼夜行", "id": 19, "trDisplay": true, "label": true, "rarity": "Special", "type": "Devil",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "劍靈", "id": 20, "trDisplay": true, "label": true, "rarity": "Special", "type": "Devil",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "軒轅劍", "id": 21, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ],
						  [ 2, 2, 2, 2, 2 ],
						  [ 0, 0, 2, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "源龍", "id": 22, "trDisplay": true, "label": true, "rarity": "Special", "type": "Dragon",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "巴比倫", "id": 23, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "玩具", "id": 24, "trDisplay": true, "label": true, "rarity": "Special", "type": "Spirit",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "童話", "id": 25, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "仙劍", "id": 26, "trDisplay": true, "label": true, "rarity": "Special", "type": "Human",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ],
						  [ 2, 2, 2, 2, 2 ],
						  [ 2, 0, 2, 2, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "天使", "id": 27, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "女武神", "id": 28, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "德魯伊", "id": 29, "trDisplay": true, "label": true, "rarity": "Special", "type": "Beast",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "北域", "id": 30, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "所羅門", "id": 31, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ],
						  [ 0, 0, 0, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "巨像", "id": 32, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 3, 3, 3, 3, 3 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "魔像", "id": 33, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "怪物彈珠", "id": 34, "trDisplay": true, "label": true, "rarity": "Special", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ],
						  [ 0, 0, 2, 0, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "魔族始源", "id": 35, "trDisplay": true, "label": true, "rarity": "Special", "type": "Devil",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "古希臘", "id": 36, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "革新英雄", "id": 37, "trDisplay": true, "label": true, "rarity": "Special", "type": "Human",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "誓約之花", "id": 38, "trDisplay": true, "label": true, "rarity": "Special", "type": "God",
		"maxLv" : 		[ [ 2, 2, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "大富翁", "id": 39, "trDisplay": true, "label": true, "rarity": "Special", "type": "Human",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 0, 1, 1, 0, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},


//================================================================================================
// rarity Boss: 地獄王系列
//================================================================================================
	{
		"name": "封王", "id": 0, "trDisplay": false, "label": true, "rarity": "Boss", "type": "Other",
		"maxLv" : 		[ [ 2, 2, 2, 2, 2 ],
						  [ 0, 1, 1, 2, 2 ],
						  [ 0, 0, 0, 0, 2 ],
						  [ 0, 0, 0, 0, 1 ]  ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "地獄魔王", "id": 1, "trDisplay": false, "label": true, "rarity": "Boss", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 2, 2 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 0, 1, 1 ],
						  [ 1, 0, 0, 1, 1 ],
						  [ 1, 0, 0, 1, 1 ],
						  [ 0, 0, 0, 1, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "合作魔王", "id": 2, "trDisplay": false, "label": true, "rarity": "Boss", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 0, 1, 1, 1, 1 ],
						  [ 0, 1, 1, 0, 1 ],
						  [ 0, 1, 0, 0, 1 ],
						  [ 0, 0, 0, 0, 1 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},


//================================================================================================
// rarity Activity: 公會任務、討伐戰等
//================================================================================================
	{
		"name": "公會任務", "id": 1, "trDisplay": false, "label": true, "rarity": "Activity", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 2, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 0, 1, 1, 1, 1 ],
						  [ 0, 1, 0, 1, 1 ] ,
						  [ 0, 0, 0, 1, 0 ]],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 1, 1, 1 ] ],
	},
	{
		"name": "討伐戰", "id": 2, "trDisplay": false, "label": true, "rarity": "Activity", "type": "Other",
		"maxLv" : 		[ [ 1, 1, 1, 1, 1 ],
						  [ 1, 1, 0, 0, 1 ],
						  [ 1, 1, 0, 0, 0 ],
						  [ 1, 0, 0, 0, 0 ] ],
		"color" : 		[ [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ],
						  [ 0, 0, 0, 0, 0 ] ],
		"tdDisplay" : 	[ [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ], 
						  [ 1, 1, 1, 1, 1 ] ],
	},
];