//==============================================================
// Character Database
//==============================================================
var CHARACTERS_DATA = {
    NONE : {
        id           : "NONE",
        label        : "瘋頭",
        img          : "img/Material/00/w1-1.png",
        color        : "w",
        type         : "MATERIAL",
        health       : 2600,
        attack       : 100,
        recovery     : 100,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "NONE",
        active       : [ "NONE" ],
    },
    PROTAGONIST_W : {
        id           : "PROTAGONIST_W",
        label        : "大魔導士莫莉",
        img          : "img/Normal/1/w4.png",
        color        : "w",
        type         : "HUMAN",
        health       : 2173,
        attack       : 1195,
        recovery     : 413,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,20], 2, [0,120,0], [1.1,4] ],
        wake_info    : [ "回復力+20", "進關後冷卻回合-2", "攻擊力+120", "4顆直排劍10%" ],
        leader       : "ELEMENT_FACTOR2_W",
        active       : [ "BREAK_BOUNDARY_W" ],
    },
    PROTAGONIST_F : {
        id           : "PROTAGONIST_F",
        label        : "龍焰騎士肖恩",
        img          : "img/Normal/1/f4.png",
        color        : "f",
        type         : "HUMAN",
        health       : 2286,
        attack       : 1278,
        recovery     : 368,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,20], 2, [0,120,0], [1.1,4] ],
        wake_info    : [ "回復力+20", "進關後冷卻回合-2", "攻擊力+120", "4顆直排劍10%" ],
        leader       : "ELEMENT_FACTOR2_F",
        active       : [ "BREAK_BOUNDARY_F" ],
    },
    PROTAGONIST_P : {
        id           : "PROTAGONIST_P",
        label        : "大地霸主鄧肯",
        img          : "img/Normal/1/p4.png",
        color        : "p",
        type         : "HUMAN",
        health       : 2513,
        attack       : 1100,
        recovery     : 386,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,20], 2, [0,120,0], [1.1,4] ],
        wake_info    : [ "回復力+20", "進關後冷卻回合-2", "攻擊力+120", "4顆直排劍10%" ],
        leader       : "ELEMENT_FACTOR2_P",
        active       : [ "BREAK_BOUNDARY_P" ],
    },
    PROTAGONIST_L : {
        id           : "PROTAGONIST_L",
        label        : "公爵奈寶尼",
        img          : "img/Normal/1/l4.png",
        color        : "l",
        type         : "HUMAN",
        health       : 2264,
        attack       : 1112,
        recovery     : 425,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,20], 2, [0,120,0], [1.1,4] ],
        wake_info    : [ "回復力+20", "進關後冷卻回合-2", "攻擊力+120", "4顆直排劍10%" ],
        leader       : "ELEMENT_FACTOR2_L",
        active       : [ "BREAK_BOUNDARY_L" ],
    },
    PROTAGONIST_D : {
        id           : "PROTAGONIST_D",
        label        : "死靈魔導安多",
        img          : "img/Normal/1/d4.png",
        color        : "d",
        type         : "HUMAN",
        health       : 2128,
        attack       : 1314,
        recovery     : 383,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,20], 2, [0,120,0], [1.1,4] ],
        wake_info    : [ "回復力+20", "進關後冷卻回合-2", "攻擊力+120", "4顆直排劍10%" ],
        leader       : "ELEMENT_FACTOR2_D",
        active       : [ "BREAK_BOUNDARY_D" ],
    },
    NORDIC_W : {
        id           : "NORDIC_W",
        label        : "咆吼戰意 ‧ 費雷",
        img          : "img/Special/1/w4.png",
        color        : "w",
        type         : "GOD",
        health       : 3556,
        attack       : 1577,
        recovery     : 496,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,30], [1.1,4], [0,180,0], [1.12,5] ],
        wake_info    : [ "回復力+30", "4顆直排劍10%", "攻擊力+180", "5顆直排劍12%" ],
        leader       : "ELEMENT_FACTOR3_W",
        active       : [ "RUNE_STRENGTHEN_W" ],
    },
    NORDIC_F : {
        id           : "NORDIC_F",
        label        : "熾焰懲責 ‧ 提爾",
        img          : "img/Special/1/f4.png",
        color        : "f",
        type         : "GOD",
        health       : 3742,
        attack       : 1686,
        recovery     : 442,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,30], [1.1,4], [0,180,0], [1.12,5] ],
        wake_info    : [ "回復力+30", "4顆直排劍10%", "攻擊力+180", "5顆直排劍12%" ],
        leader       : "ELEMENT_FACTOR3_F",
        active       : [ "RUNE_STRENGTHEN_F" ],
    },
    NORDIC_P : {
        id           : "NORDIC_P",
        label        : "悼靈之喚 ‧ 費蕾雅",
        img          : "img/Special/1/p4.png",
        color        : "p",
        type         : "GOD",
        health       : 3961,
        attack       : 1529,
        recovery     : 464,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,30], [1.1,4], [0,180,0], [1.12,5] ],
        wake_info    : [ "回復力+30", "4顆直排劍10%", "攻擊力+180", "5顆直排劍12%" ],
        leader       : "ELEMENT_FACTOR3_P",
        active       : [ "RUNE_STRENGTHEN_P" ],
    },
    NORDIC_L : {
        id           : "NORDIC_L",
        label        : "閃爍鳴動 ‧ 索爾",
        img          : "img/Special/1/l4.png",
        color        : "l",
        type         : "GOD",
        health       : 3738,
        attack       : 1545,
        recovery     : 531,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,30], [1.1,4], [0,180,0], [1.12,5] ],
        wake_info    : [ "回復力+30", "4顆直排劍10%", "攻擊力+180", "5顆直排劍12%" ],
        leader       : "ELEMENT_FACTOR3_L",    
        active       : [ "RUNE_STRENGTHEN_L" ],
    },
    NORDIC_D : {
        id           : "NORDIC_D",
        label        : "不赦惡神 ‧ 洛基",
        img          : "img/Special/1/d4.png",
        color        : "d",
        type         : "GOD",
        health       : 3482,
        attack       : 1734,
        recovery     : 460,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,30], [1.1,4], [0,180,0], [1.12,5] ],
        wake_info    : [ "回復力+30", "4顆直排劍10%", "攻擊力+180", "5顆直排劍12%" ],
        leader       : "ELEMENT_FACTOR3_D",
        active       : [ "RUNE_STRENGTHEN_D" ],
    },
    BOSS_ODIN : {
        id           : "BOSS_ODIN",
        label        : "永恆之槍 ‧ 主神奧丁",
        img          : "img/Boss/0/d2-3.png",
        color        : "d",
        type         : "GOD",
        health       : 4259,
        attack       : 1995,
        recovery     : 352,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "WILL_SURVIVE",
        active       : [ "DESPERATE_ATTACK" ],
    },
    BOSS_SOLAR_DESTROYER_SIRIUS : {
        id           : "BOSS_SOLAR_DESTROYER_SIRIUS",
        label        : "噬日誅天 ‧ 噬日狼",
        img          : "img/Boss/0/l2-1.png",
        color        : "l",
        type         : "BEAST",
        health       : 3451,
        attack       : 1658,
        recovery     : 222,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "STRONG_WILL_LIGHT",
        active       : [ "POSS_LIGHT_SPIRIT", "COMMAND_OF_LORDS" ],
    },
    BOSS_LUNAR_DESTROYER_SIRIUS : {
        id           : "BOSS_LUNAR_DESTROYER_SIRIUS",
        label        : "蝕月毀天 ‧ 喰月狼",
        img          : "img/Boss/0/d2-2.png",
        color        : "d",
        type         : "BEAST",
        health       : 3245,
        attack       : 1864,
        recovery     : 200,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "STRONG_WILL_DARK",
        active       : [ "POSS_DARK_SPIRIT", "COMMAND_OF_DEVILS" ],
    },
    CHINA_D : {
        id           : "CHINA_D",
        label        : "善心狐仙 ‧ 蘇妲己",
        img          : "img/Special/4/d5.png",
        color        : "d",
        type         : "SPIRIT",
        health       : 2353,
        attack       : 1407,
        recovery     : 786,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,50], [1.1,3], [0,100,0], [1.1,4] ],
        wake_info    : [ "回復力+50", "3顆直排心10%", "攻擊力+100", "4顆直排劍10%" ],
        leader       : "CHINA_D",
        active       : [ "OVER_BEAUTY" ],
    },
    GREEK_W : {
        id           : "GREEK_W",
        label        : "大海之神 ‧ 波塞頓",
        img          : "img/Special/2/w3.png",
        color        : "w",
        type         : "GOD",
        health       : 2927,
        attack       : 1646,
        recovery     : 403,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], [1.1,4], [340,0,0], ['w',0.4] ],
        wake_info    : [ "攻擊力+90", "4顆直排劍10%", "生命力+340", "直排水符石掉落提升至40%" ],
        leader       : "GREEK_W",
        active       : [ "TRACE_OF_NOTION_W" ],
    },
    GREEK_F : {
        id           : "GREEK_F",
        label        : "煉火之神 ‧ 赫淮斯托斯",
        img          : "img/Special/2/f3.png",
        color        : "f",
        type         : "GOD",
        health       : 3080,
        attack       : 1760,
        recovery     : 358,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], [1.1,4], [340,0,0], ['f',0.4] ],
        wake_info    : [ "攻擊力+90", "4顆直排劍10%", "生命力+340", "直排火符石掉落提升至40%" ],
        leader       : "GREEK_F",
        active       : [ "TRACE_OF_NOTION_F" ],
    },
    GREEK_P : {
        id           : "GREEK_P",
        label        : "戰爭女神 ‧ 雅典娜",
        img          : "img/Special/2/p3.png",
        color        : "p",
        type         : "GOD",
        health       : 3385,
        attack       : 1516,
        recovery     : 376,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], [1.1,4], [340,0,0], ['p',0.4] ],
        wake_info    : [ "攻擊力+90", "4顆直排劍10%", "生命力+340", "直排木符石掉落提升至40%" ],
        leader       : "GREEK_P",
        active       : [ "TRACE_OF_NOTION_P" ],
    },
    GREEK_L : {
        id           : "GREEK_L",
        label        : "聖光之神 ‧ 阿波羅",
        img          : "img/Special/2/l3.png",
        color        : "l",
        type         : "GOD",
        health       : 3049,
        attack       : 1634,
        recovery     : 414,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], [1.1,4], [340,0,0], ['l',0.4] ],
        wake_info    : [ "攻擊力+90", "4顆直排劍10%", "生命力+340", "直排光符石掉落提升至40%" ],
        leader       : "GREEK_L",
        active       : [ "TRACE_OF_NOTION_L" ],
    },
    GREEK_D : {
        id           : "GREEK_D",
        label        : "月夜之神 ‧ 阿提密斯",
        img          : "img/Special/2/d3.png",
        color        : "d",
        type         : "GOD",
        health       : 2866,
        attack       : 1810,
        recovery     : 373,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], [1.1,4], [340,0,0], ['d',0.4] ],
        wake_info    : [ "攻擊力+90", "4顆直排劍10%", "生命力+340", "直排暗符石掉落提升至40%" ],
        leader       : "GREEK_D",
        active       : [ "TRACE_OF_NOTION_D" ],
    },
    HEART_QUEEN : {
        id           : "HEART_QUEEN",
        label        : "魔境之主 ‧ 紅心女王",
        img          : "img/Boss/1/f1-1.png",
        color        : "f",
        type         : "HUMAN",
        health       : 1954,
        attack       : 1392,
        recovery     : 431,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "HEART_QUEEN",
        active       : [ "TRANSFIGURATION_H" ],
    },
    EGG_SPIRIT_W : {
        id           : "EGG_SPIRIT_W",
        label        : "驚喜創造 ‧ 伊德海拉",
        img          : "img/Special/6/w4.png",
        color        : "w",
        type         : "SPIRIT",
        health       : 1180,
        attack       : 959,
        recovery     : 442,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "CHANGE_ACTIVE_SKILL" ],
        wake_var     : [ [0,0,50], [1.1,3], [0,0,100], [0,"BIBBLE_BURST_EX"] ],
        wake_info    : [ "回復力+50", "3顆直排心10%", "回復力+100", "主動技變為 爆裂之幻沫" ],
        leader       : "SPIRIT_RECOVER_FACTOR_2",
        active       : [ "BIBBLE_BURST" ],
    },
    EGG_SPIRIT_F : {
        id           : "EGG_SPIRIT_F",
        label        : "冬日暖燈 ‧ 梅格蘭斯",
        img          : "img/Special/6/f4.png",
        color        : "f",
        type         : "SPIRIT",
        health       : 1242,
        attack       : 1026,
        recovery     : 393,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,0,50], [1.1,3], [0,0,100], ['h',0.25] ],
        wake_info    : [ "回復力+50", "3顆直排心10%", "回復力+100", "直排心符石掉落提升至25%" ],
        leader       : "SPIRIT_FACTOR_2",
        active       : [ "IGNITION" ],
    },
    EGG_SPIRIT_P : {
        id           : "EGG_SPIRIT_P",
        label        : "七彩琉璃 ‧ 伊薇特",
        img          : "img/Special/6/p4.png",
        color        : "p",
        type         : "SPIRIT",
        health       : 1365,
        attack       : 884,
        recovery     : 413,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "CHANGE_ACTIVE_SKILL" ],
        wake_var     : [ [0,0,50], [1.05,3], [0,0,100], [0,"HARVEST_OF_LIFE_EX"] ],
        wake_info    : [ "回復力+50", "3顆直排心5%", "回復力+100", "主動技變為 生靈採捕" ],
        leader       : "SPIRIT_HEALTH_FACTOR_2",
        active       : [ "HARVEST_OF_LIFE" ],
    },
    EGG_SPIRIT_L : {
        id           : "EGG_SPIRIT_L",
        label        : "頌慶佳音 ‧ 瑪格莉特",
        img          : "img/Special/6/l4.png",
        color        : "l",
        type         : "SPIRIT",
        health       : 1229,
        attack       : 893,
        recovery     : 454,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "CHANGE_ACTIVE_SKILL" ],
        wake_var     : [ [0,0,50], [1.05,3], [0,0,100], [0,"PREVASION_EX"] ],
        wake_info    : [ "回復力+50", "3顆直排心10%", "回復力+100", "主動技變為 傳播" ],
        leader       : "SPIRIT_RECOVER_FACTOR_2",
        active       : [ "PREVASION" ],
    },
    EGG_SPIRIT_D : {
        id           : "EGG_SPIRIT_D",
        label        : "祝福分派 ‧ 伊莎貝爾",
        img          : "img/Special/6/d4.png",
        color        : "d",
        type         : "SPIRIT",
        health       : 986,
        attack       : 793,
        recovery     : 393,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING" ],
        wake_var     : [ [0,0,50], [1.05,3], [0,0,100], 3 ],
        wake_info    : [ "回復力+50", "3顆直排心10%", "回復力+100", "進關後冷卻回合-3" ],
        leader       : "SPIRIT_FACTOR_2",
        active       : [ "BEWITCHMENT" ],
    },
    BOSS_DIABLO      : {        
        id           : "BOSS_DIABLO",
        label        : "噩耗元素噬者 ‧ 迪亞布羅",
        img          : "img/Boss/0/f2-1.png",
        color        : "f",
        type         : "SPIRIT",
        health       : 2775,
        attack       : 1483,
        recovery     : 1027,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "CASTIGATION_OF_SIN",
        active       : [ "NOXIOUS_REPLACEMENT_HEART", "PLUNDER_OF_LIFE" ],
    },
    ETHEREAL_DRAGON_W : {
        id           : "ETHEREAL_DRAGON_W",
        label        : "深潛之主宰 ‧ 達貢",
        img          : "img/Special/7/w3.png",
        color        : "w",
        type         : "DRAGON",
        health       : 3618,
        attack       : 1190,
        recovery     : 129,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], 1, [500,0,0], ['h',0.25] ],
        wake_info    : [ "攻擊力+90", "進關後冷卻回合-1", "生命力+500", "直排心符石掉落提升至25%" ],
        leader       : "DRAGON_OFFENSE",
        active       : [ "DEFENSIVE_STANCE_W" ],
    },
    ETHEREAL_DRAGON_F : {
        id           : "ETHEREAL_DRAGON_F",
        label        : "冥炎之子嗣 ‧ 克圖格亞",
        img          : "img/Special/7/f3.png",
        color        : "f",
        type         : "DRAGON",
        health       : 3625,
        attack       : 1273,
        recovery     : 115,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], 1, [500,0,0], ['h',0.25] ],
        wake_info    : [ "攻擊力+90", "進關後冷卻回合-1", "生命力+500", "直排心符石掉落提升至25%" ],
        leader       : "DRAGON_OFFENSE",
        active       : [ "DEFENSIVE_STANCE_F" ],
    },
    ETHEREAL_DRAGON_P : {
        id           : "ETHEREAL_DRAGON_P",
        label        : "撕星怒嘯者 ‧ 拜亞基",
        img          : "img/Special/7/p3.png",
        color        : "p",
        type         : "DRAGON",
        health       : 3984,
        attack       : 1096,
        recovery     : 121,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], 1, [500,0,0], ['h',0.25] ],
        wake_info    : [ "攻擊力+90", "進關後冷卻回合-1", "生命力+500", "直排心符石掉落提升至25%" ],
        leader       : "DRAGON_OFFENSE",
        active       : [ "DEFENSIVE_STANCE_P" ],
    },
    ETHEREAL_DRAGON_L : {
        id           : "ETHEREAL_DRAGON_L",
        label        : "捕芒之聖主 ‧ 圖爾茲查",
        img          : "img/Special/7/l3.png",
        color        : "l",
        type         : "DRAGON",
        health       : 3697,
        attack       : 1108,
        recovery     : 133,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], 2, [500,0,0], ['h',0.25] ],
        wake_info    : [ "攻擊力+90", "進關後冷卻回合-2", "生命力+500", "直排心符石掉落提升至25%" ],
        leader       : "PULSE_OF_DRAGON",
        active       : [ "THUNDER_STRIKE_EX" ],
    },
    ETHEREAL_DRAGON_D : {
        id           : "ETHEREAL_DRAGON_D",
        label        : "怖慄飼食者 ‧ 法格恩",
        img          : "img/Special/7/d3.png",
        color        : "d",
        type         : "DRAGON",
        health       : 3373,
        attack       : 1308,
        recovery     : 120,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [0,90,0], 2, [500,0,0], ['h',0.25] ],
        wake_info    : [ "攻擊力+90", "進關後冷卻回合-2", "生命力+500", "直排心符石掉落提升至25%" ],
        leader       : "DRAGON_DEFENSE",
        active       : [ "DARKNESS_ASSAULT_EX" ],
    },
    DRAGON_SERVANT_W : {
        id           : "DRAGON_SERVANT_W",
        label        : "蒼海的迴聲 ‧ 烏蘇拉",
        img          : "img/Special/11/w3.png",
        color        : "w",
        type         : "DRAGON",
        health       : 3754,
        attack       : 1345,
        recovery     : 176,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,90,0], [1.1,3], [500,0,0], [1.1,4] ],
        wake_info    : [ "攻擊力+90", "3顆直排劍10%", "生命力+500", "4顆直排劍10%" ],
        leader       : "BLOOD_THIRSTY_DRAGON_EX",
        active       : [ "DRAGON_RESONANCE" ],
    },
    DRAGON_SERVANT_F : {
        id           : "DRAGON_SERVANT_F",
        label        : "赤焰的領袖 ‧ 愛格德",
        img          : "img/Special/11/f3.png",
        color        : "f",
        type         : "DRAGON",
        health       : 3874,
        attack       : 1400,
        recovery     : 153,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,90,0], [1.1,3], [500,0,0], [1.1,4] ],
        wake_info    : [ "攻擊力+90", "3顆直排劍10%", "生命力+500", "4顆直排劍10%" ],
        leader       : "FANGS_OF_DRAGON",
        active       : [ "ATTACK_REINFORCEMENT_F" ],
    },
    DRAGON_SERVANT_P : {
        id           : "DRAGON_SERVANT_P",
        label        : "青林的風祭 ‧ 芭芭拉",
        img          : "img/Special/11/p3.png",
        color        : "p",
        type         : "DRAGON",
        health       : 4175,
        attack       : 1201,
        recovery     : 158,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,90,0], [1.1,3], [500,0,0], [1.1,4] ],
        wake_info    : [ "攻擊力+90", "3顆直排劍10%", "生命力+500", "4顆直排劍10%" ],
        leader       : "BLOOD_THIRSTY_DRAGON_EX",
        active       : [ "DRAGON_SHIELD" ],
    },
    DRAGON_SERVANT_L : {
        id           : "DRAGON_SERVANT_L",
        label        : "永恆的聖焰 ‧ 安納",
        img          : "img/Special/11/l3.png",
        color        : "l",
        type         : "DRAGON",
        health       : 3948,
        attack       : 1264,
        recovery     : 182,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,90,0], [1.1,3], [500,0,0], [1.1,4] ],
        wake_info    : [ "攻擊力+90", "3顆直排劍10%", "生命力+500", "4顆直排劍10%" ],
        leader       : "CLAWS_OF_DRAGON",
        active       : [ "ATTACK_REINFORCEMENT_L" ],
    },
    DRAGON_SERVANT_D : {
        id           : "DRAGON_SERVANT_D",
        label        : "闇噬的蘊量 ‧ 諾瓦利斯",
        img          : "img/Special/11/d3.png",
        color        : "d",
        type         : "DRAGON",
        health       : 3606,
        attack       : 1450,
        recovery     : 160,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,90,0], [1.1,3], [500,0,0], [1.1,4] ],
        wake_info    : [ "攻擊力+90", "3顆直排劍10%", "生命力+500", "4顆直排劍10%" ],
        leader       : "FANGS_OF_DRAGON",
        active       : [ "DRAGON_CENTRALIZATION_D_EX" ],
    },
    BOSS_DRAGON_NIDHOGG : {
        id           : "BOSS_DRAGON_NIDHOGG",
        label        : "末日屍龍 ‧ 尼德霍格",
        img          : "img/Boss/0/p2-1.png",
        color        : "p",
        type         : "DRAGON",
        health       : 7503,
        attack       : 1877,
        recovery     : 0,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "OATH_OF_BLOOD",
        active       : [ "COURAGE_OF_SACRIFICE", "REVIVAL_OF_SPIRIT_DRAGON" ],
    },
    COUPLE_F : {
        id           : "COUPLE_F",
        label        : "彌勒世尊 ‧ 燃燈",
        img          : "img/Special/15/f3.png",
        color        : "f",
        type         : "GOD",
        health       : 3102,
        attack       : 1604,
        recovery     : 376,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ENCIRCLEMENT", "H_A_R_INCREASE", "STRAIGHT_ENCHANTMENT" ],
        wake_var     : [ [0,90,0], 'h', [340,0,0], 'h' ],
        wake_info    : [ "攻擊力+90", "直排靈氣圍城", "生命力+340", "直排心強化" ],
        leader       : "COUPLE_F",
        active       : [ "DEFENSIVE_STANCE_EX_F" ],
    },
    COUPLE_P : {
        id           : "COUPLE_P",
        label        : "顯聖真君 ‧ 楊戩",
        img          : "img/Special/15/p3.png",
        color        : "p",
        type         : "HUMAN",
        health       : 3132,
        attack       : 1372,
        recovery     : 384,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [0,0,50], 2, [0,120,0], [1.1,4] ],
        wake_info    : [ "回復力+50", "進關後冷卻回合-2", "攻擊力+120", "4顆直排劍10%" ],
        leader       : "COUPLE_P",
        active       : [ "BATTLEFIELD_P" ],
    },
    MACHINE_DOLL_W : {
        id           : "MACHINE_DOLL_W",
        label        : "連肢機偶 · 格蕾琴與海森堡",
        img          : "img/Special/17/w2.png",
        color        : "w",
        type         : "HUMAN",
        health       : 2595,
        attack       : 1267,
        recovery     : 342,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [90,0,0], 2, [0,120,0], [1.1,3] ],
        wake_info    : [ "生命力+90", "進關後冷卻回合-2", "攻擊力+120", "3顆直排劍10%" ],
        leader       : "DOLL_HUMAN_DRAGON" ,
        active       : [ "FIGHT_SAFE" ],
    },
    MACHINE_DOLL_F : {
        id           : "MACHINE_DOLL_F",
        label        : "焚魔學者 ‧ 阿涅茜",
        img          : "img/Special/17/f2.png",
        color        : "f",
        type         : "HUMAN",
        health       : 2731,
        attack       : 1355,
        recovery     : 304,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [90,0,0], 2, [0,120,0], [1.1,3] ],
        wake_info    : [ "生命力+90", "進關後冷卻回合-2", "攻擊力+120", "3顆直排劍10%" ],
        leader       : "DOLL_HUMAN_DRAGON" ,
        active       : [ "FIGHT_SAFE" ],
    },
    MACHINE_DOLL_P : {
        id           : "MACHINE_DOLL_P",
        label        : "蠻牛貳式",
        img          : "img/Special/17/p2.png",
        color        : "p",
        type         : "HUMAN",
        health       : 3001,
        attack       : 1167,
        recovery     : 320,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [90,0,0], 2, [0,120,0], [1.1,3] ],
        wake_info    : [ "生命力+90", "進關後冷卻回合-2", "攻擊力+120", "3顆直排劍10%" ],
        leader       : "DOLL_HUMAN_BEAST_SPIRIT" ,
        active       : [ "PLAY_WILD" ],
    },
    MACHINE_DOLL_L : {
        id           : "MACHINE_DOLL_L",
        label        : "半偶研製者 ‧ 莉莎",
        img          : "img/Special/17/l2.png",
        color        : "l",
        type         : "HUMAN",
        health       : 2704,
        attack       : 1179,
        recovery     : 352,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [90,0,0], 2, [0,120,0], [1.1,3] ],
        wake_info    : [ "生命力+90", "進關後冷卻回合-2", "攻擊力+120", "3顆直排劍10%" ],
        leader       : "DOLL_HUMAN_DEVIL_SPIRIT" ,
        active       : [ "PLAY_SAFE" ],
    },
    MACHINE_DOLL_D : {
        id           : "MACHINE_DOLL_D",
        label        : "偏狂學士 ‧ 米基利",
        img          : "img/Special/17/d2.png",
        color        : "d",
        type         : "HUMAN",
        health       : 2541,
        attack       : 1393,
        recovery     : 317,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [90,0,0], 2, [0,120,0], [1.1,3] ],
        wake_info    : [ "生命力+90", "進關後冷卻回合-2", "攻擊力+120", "3顆直排劍10%" ],
        leader       : "DOLL_HUMAN_GOD" ,
        active       : [ "PLAY_WILD" ],
    },
    TRIBE_BEAST_W : {
        id           : "TRIBE_BEAST_W",
        label        : "部落勇士 ‧ 奧托",
        img          : "img/Special/18/w3.png",
        color        : "w",
        type         : "BEAST",
        health       : 2896,
        attack       : 1173,
        recovery     : 153,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_HEAL"],
        wake_var     : [ [0,70,0], [1.1,3], [360,0,0], [10,4] ],
        wake_info    : [ "攻擊力+70", "3顆直排劍10%", "生命力+360", "4顆直排10倍回血" ],
        leader       : "TRIBE_BEAST_W",
        active       : [ "HUNTING_MODE" ],
    },
    TRIBE_BEAST_F : {
        id           : "TRIBE_BEAST_F",
        label        : "部落智者 ‧ 伊奇多",
        img          : "img/Special/18/f3.png",
        color        : "f",
        type         : "BEAST",
        health       : 3006,
        attack       : 1239,
        recovery     : 135,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_BEGINING", "H_A_R_INCREASE", "STRAIGHT_HEAL"],
        wake_var     : [ [0,70,0], 7, [360,0,0], [10,4] ],
        wake_info    : [ "攻擊力+70", "進關後冷卻回合-7", "生命力+360", "4顆直排10倍回血" ],
        leader       : "TRIBE_BEAST_F",
        active       : [ "BLAZING_CIRCLE" ],
    },
    TRIBE_BEAST_P : {
        id           : "TRIBE_BEAST_P",
        label        : "部落首領 ‧ 木法沙",
        img          : "img/Special/18/p3.png",
        color        : "p",
        type         : "BEAST",
        health       : 3304,
        attack       : 1066,
        recovery     : 141,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_HEAL"],
        wake_var     : [ [0,70,0], [1.1,3], [360,0,0], [10,4] ],
        wake_info    : [ "攻擊力+70", "3顆直排劍10%", "生命力+360", "4顆直排10倍回血" ],
        leader       : "TRIBE_BEAST_P",
        active       : [ "SAVAGE_ATTACK" ],
    },
    TRIBE_BEAST_L : {
        id           : "TRIBE_BEAST_L",
        label        : "天空俠盜 ‧ 布瑪",
        img          : "img/Special/18/l3.png",
        color        : "l",
        type         : "BEAST",
        health       : 3017,
        attack       : 1092,
        recovery     : 158,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_HEAL"],
        wake_var     : [ [0,70,0], [1.1,3], [360,0,0], [10,4] ],
        wake_info    : [ "攻擊力+70", "3顆直排劍10%", "生命力+360", "4顆直排10倍回血" ],
        leader       : "TRIBE_BEAST_L",
        active       : [ "HUNTING_MODE" ],
    },
    TRIBE_BEAST_D : {
        id           : "TRIBE_BEAST_D",
        label        : "月詠美神 ‧ 芭絲蒂",
        img          : "img/Special/18/d3.png",
        color        : "d",
        type         : "BEAST",
        health       : 2798,
        attack       : 1273,
        recovery     : 140,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "H_A_R_INCREASE", "STRAIGHT_HEAL"],
        wake_var     : [ [0,70,0], [1.1,3], [360,0,0], [10,4] ],
        wake_info    : [ "攻擊力+70", "3顆直排劍10%", "生命力+360", "4顆直排10倍回血" ],
        leader       : "TRIBE_BEAST_D",
        active       : [ "SAVAGE_ATTACK" ],
    },
    BABYLON_W : {
        id           : "BABYLON_W",
        label        : "智慧者 ‧ 阿特拉哈西斯",
        img          : "img/Special/23/w2.png",
        color        : "w",
        type         : "GOD",
        health       : 3011,
        attack       : 1399,
        recovery     : 421,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "BABYLON_W",
        active       : [ "BLADES_OF_WATER" ],
    },
    BABYLON_F : {
        id           : "BABYLON_F",
        label        : "暴風軍神 ‧ 尼努爾塔",
        img          : "img/Special/23/f2.png",
        color        : "f",
        type         : "GOD",
        health       : 3167,
        attack       : 1496,
        recovery     : 375,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "BABYLON_F",
        active       : [ "BLADES_OF_FLAME" ],
    },
    BABYLON_P : {
        id           : "BABYLON_P",
        label        : "牧者國王 ‧ 杜穆濟",
        img          : "img/Special/23/p2.png",
        color        : "p",
        type         : "GOD",
        health       : 3481,
        attack       : 1288,
        recovery     : 394,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "BABYLON_P",
        active       : [ "BLADES_OF_VINE" ],
    },
    BABYLON_L : {
        id           : "BABYLON_L",
        label        : "月神 ‧ 伊南娜",
        img          : "img/Special/23/l2.png",
        color        : "l",
        type         : "GOD",
        health       : 3136,
        attack       : 1302,
        recovery     : 433,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "BABYLON_L",
        active       : [ "BLADES_OF_LIGHT" ],
    },
    BABYLON_D : {
        id           : "BABYLON_D",
        label        : "惡疾之神 ‧ 納姆塔爾",
        img          : "img/Special/23/d2.png",
        color        : "d",
        type         : "GOD",
        health       : 2948,
        attack       : 1537,
        recovery     : 390,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "BABYLON_D",
        active       : [ "BLADES_OF_PHANTOM" ],
    },
    SWORD_BROTHER : {
        id           : "SWORD_BROTHER",
        label        : "軒轅聖劍 ‧ 皇甫朝雲與皇甫暮雲",
        img          : "img/Special/21/d2-2.png",
        color        : "d",
        type         : "HUMAN",
        health       : 2393,
        attack       : 1560,
        recovery     : 431,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "DROP_INCREASE", "CHANGE_LEADER_SKILL" ],
        wake_var     : [ [150,120,0], [1.1,3], ['d',0.4], "SWORD_BROTHER_EX" ],
        wake_info    : [ "攻擊力+120;生命力+150", "3顆直排劍10%", "直排暗符石掉落提升至40%", "隊長技改為陰陽煞陣 ‧ 強" ],
        leader       : "SWORD_BROTHER",
        active       : [ "ENSIFORM_BREATH" ],
    },
    ZHAOLINGER : {
        id           : "ZHAOLINGER",
        label        : "女媧仙蓮 ‧ 趙靈兒",
        img          : "img/Special/26/w2-1.png",
        color        : "w",
        type         : "HUMAN",
        health       : 2349,
        attack       : 1360,
        recovery     : 477,
        wake         : [ "H_A_R_INCREASE", "ACTIVE_COOLDOWN_FOREVER", "H_A_R_INCREASE", "CHANGE_LEADER_SKILL" ],
        wake_var     : [ [150,0,0], 2, [0,120,0], "COMMON_SOURCE_EX" ],
        wake_info    : [ "生命力+150", "冷卻回合永久-2", "攻擊力+120", "隊長技變為仙劍同源 ‧ 強" ],
        leader       : "COMMON_SOURCE",
        active       : [ "SPELL_OF_TORNADOS" ],
    },
    LINYUERU : {
        id           : "LINYUERU",
        label        : "武道女俠 ‧ 林月如",
        img          : "img/Special/26/f2-1.png",
        color        : "f",
        type         : "HUMAN",
        health       : 2472,
        attack       : 1455,
        recovery     : 424,
        wake         : [ "H_A_R_INCREASE", "CHANGE_ACTIVE_SKILL", "H_A_R_INCREASE", "CHANGE_LEADER_SKILL" ],
        wake_var     : [ [100,0,0], [0,"SPELL_OF_BLOOD_SPIRITS_EX"], [0,130,0], "COMMON_SOURCE_EX" ],
        wake_info    : [ "生命力+100", "主動技變為靈血咒 ‧ 強", "攻擊力+130", "隊長技變為仙劍同源 ‧ 強" ],
        leader       : "COMMON_SOURCE",
        active       : [ "SPELL_OF_BLOOD_SPIRITS" ],
    },
    LIXIAOYAO : {
        id           : "LIXIAOYAO",
        label        : "蜀山劍仙 ‧ 李逍遙",
        img          : "img/Special/26/p2-1.png",
        color        : "p",
        type         : "HUMAN",
        health       : 2805,
        attack       : 1358,
        recovery     : 440,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "STRAIGHT_ATTACK", "ACTIVE_COOLDOWN_BEGINING" ],
        wake_var     : [ [150,80,0], [1.1,3], [1.1,4], 2 ],
        wake_info    : [ "攻擊力+80;生命力+150", "3顆直排心10%", "4顆直排劍10%", "進關後冷卻回合-2" ],
        leader       : "LIXIAOYAO",
        active       : [ "DRUNKEN_FOOTWORK" ],
    },
    WATER_FAIRY : {
        id           : "WATER_FAIRY",
        label        : "水精靈仙女 忒琪菈",
        img          : "img/Special/34/w1-1.png",
        color        : "w",
        type         : "SPIRIT",
        health       : 2145,
        attack       : 1240,
        recovery     : 651,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "DROP_INCREASE" ],
        wake_var     : [ [110,0,0], [1.1,4], [0,110,0], ['h',0.25] ],
        wake_info    : [ "生命力+110", "4顆直排心10%", "攻擊力+110", "直排心符石掉落提升至25%" ],
        leader       : "WATER_FAIRY",
        active       : [ "WATER_FAIRY" ],
    },
    DARK_LUCIFER : {
        id           : "DARK_LUCIFER",
        label        : "反叛的墮天使 路西法",
        img          : "img/Special/34/d1-2.png",
        color        : "d",
        type         : "SPIRIT",
        health       : 2416,
        attack       : 1485,
        recovery     : 601,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_RECOVER", "H_A_R_INCREASE", "STRAIGHT_ATTACK" ],
        wake_var     : [ [110,0,0], [1.1,4], [0,110,0], [1.1,4] ],
        wake_info    : [ "生命力+110", "4顆直排心10%", "攻擊力+110", "4顆直排劍10%" ],
        leader       : "DARK_LUCIFER",
        active       : [ "SONG_OF_EMPATHY_EVIL"],
    },
    DEVIL_ANCESTOR_W : {
        id           : "DEVIL_ANCESTOR_W",
        label        : "代罪之泉 ‧ 阿撒茲勒",
        img          : "img/Special/35/w2.png",
        color        : "w",
        type         : "DEVIL",
        health       : 1651,
        attack       : 2362,
        recovery     : 396,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "DEVIL_ILLUSION_W",
        active       : [ "ELEMENTAL_ASSEMBLY_W" ],
    },
    DEVIL_ANCESTOR_F : {
        id           : "DEVIL_ANCESTOR_F",
        label        : "毀滅之炎 ‧ 亞巴頓",
        img          : "img/Special/35/f2.png",
        color        : "f",
        type         : "DEVIL",
        health       : 1724,
        attack       : 2429,
        recovery     : 330,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "DEVIL_ILLUSION_F",
        active       : [ "ELEMENTAL_ASSEMBLY_F" ],
    },
    DEVIL_ANCESTOR_P : {
        id           : "DEVIL_ANCESTOR_P",
        label        : "盤木智者 ‧ 薩麥爾",
        img          : "img/Special/35/p2.png",
        color        : "p",
        type         : "DEVIL",
        health       : 1895,
        attack       : 2279,
        recovery     : 368,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "DEVIL_ILLUSION_P",
        active       : [ "ELEMENTAL_ASSEMBLY_P" ],
    },
    DEVIL_ANCESTOR_L : {
        id           : "DEVIL_ANCESTOR_L",
        label        : "蒼蠅之王 ‧ 別西卜",
        img          : "img/Special/35/l2.png",
        color        : "l",
        type         : "DEVIL",
        health       : 1698,
        attack       : 2315,
        recovery     : 408,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "DEVIL_CIRCLE_L",
        active       : [ "MAGIC_STAGE_BEAM" ],
    },
    DEVIL_ANCESTOR_D : {
        id           : "DEVIL_ANCESTOR_D",
        label        : "邪心之靈 ‧ 莫斯提馬",
        img          : "img/Special/35/d2.png",
        color        : "d",
        type         : "DEVIL",
        health       : 1582,
        attack       : 2531,
        recovery     : 304,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "無", "無", "無", "無" ],
        leader       : "DEVIL_CIRCLE_D",
        active       : [ "MAGIC_STAGE_GLOOM" ],
    },
    BOSS_YOG_SOTHOTH : {
        id           : "BOSS_YOG_SOTHOTH",
        label        : "虛空建構者 ‧ 猶格索托斯",
        img          : "img/Boss/0/f1-2.png",
        color        : "f",
        type         : "DEVIL",
        health       : 2265,
        attack       : 3050,
        recovery     : 427,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "", "", "", "" ],
        leader       : "ELEMENTAL_AGGRESSION",
        active       : [ "MASTERY_OF_ELEMENTS" ],
    },
    OLD_GREEK_W : {
        id           : "OLD_GREEK_W",
        label        : "浪濤海神 ‧ 蓬托斯",
        img          : "img/Special/36/w2.png",
        color        : "w",
        type         : "GOD",
        health       : 2769,
        attack       : 1486,
        recovery     : 433,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "", "", "", "" ],
        leader       : "OLD_GREEK_WD",
        active       : [ "FLORAL_CORNER_W" ],
    },
    OLD_GREEK_F : {
        id           : "OLD_GREEK_F",
        label        : "熽焰火神 ‧ 法那斯",
        img          : "img/Special/36/f2.png",
        color        : "f",
        type         : "GOD",
        health       : 2853,
        attack       : 1582,
        recovery     : 349,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "", "", "", "" ],
        leader       : "ELEMENT_FACTOR4_F",
        active       : [ "TREATY_OF_OLD_GREEK_F" ],
    },
    OLD_GREEK_P : {
        id           : "OLD_GREEK_P",
        label        : "大地女神 ‧ 蓋婭",
        img          : "img/Special/36/p2.png",
        color        : "p",
        type         : "GOD",
        health       : 3178,
        attack       : 1355,
        recovery     : 390,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "", "", "", "" ],
        leader       : "ELEMENT_FACTOR4_P",
        active       : [ "TREATY_OF_OLD_GREEK_P" ],
    },
    OLD_GREEK_L : {
        id           : "OLD_GREEK_L",
        label        : "星護女神 ‧ 埃忒耳",
        img          : "img/Special/36/l2.png",
        color        : "l",
        type         : "GOD",
        health       : 3027,
        attack       : 1365,
        recovery     : 428,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "", "", "", "" ],
        leader       : "OLD_GREEK_L",
        active       : [ "QUINTUPLE_COHERENCE" ],
    },
    OLD_GREEK_D : {
        id           : "OLD_GREEK_D",
        label        : "暗影夜神 ‧ 厄瑞玻斯",
        img          : "img/Special/36/d2.png",
        color        : "d",
        type         : "GOD",
        health       : 2775,
        attack       : 1653,
        recovery     : 330,
        wake         : [ "NONE", "NONE", "NONE", "NONE" ],
        wake_var     : [ 0, 0, 0, 0 ],
        wake_info    : [ "", "", "", "" ],
        leader       : "OLD_GREEK_WD",
        active       : [ "FLORAL_CORNER_D" ],
    },

// @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
// CREATURE
    BOSS_ODIN_CREATURE_1 : {
        id           : "BOSS_ODIN_CREATURE_1",
        label        : "永恆之槍 ‧ 主神奧丁",
        img          : "img/Creature/BossOdin01.png",
        color        : "d",
        type         : "GOD",
        health       : 4259,
        attack       : 1995,
        recovery     : 352,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "ACTIVE_COOLDOWN_FOREVER", "DROP_INCREASE" ],
        wake_var     : [ [500,300,150], [1.2,5], 4, ['h', 0.25] ],
        wake_info    : [ "生命力+500;攻擊力+300;回復力+150", "5顆直排劍20%", "冷卻回合永久-4", "直排心符石掉落提升至25%" ],
        leader       : "WILL_SURVIVE",
        active       : [ "DESPERATE_ATTACK", "RUNE_STRONG_SWITCH" ],
    },
    BOSS_ODIN_CREATURE_2 : {
        id           : "BOSS_ODIN_CREATURE_2",
        label        : "永恆之槍 ‧ 主神奧丁",
        img          : "img/Creature/BossOdin02.png",
        color        : "d",
        type         : "GOD",
        health       : 4259,
        attack       : 1995,
        recovery     : 352,
        wake         : [ "H_A_R_INCREASE", "STRAIGHT_ATTACK", "ACTIVE_COOLDOWN_FOREVER", "DROP_INCREASE" ],
        wake_var     : [ [500,300,150], [1.2,5], 4, ['h', 0.25] ],
        wake_info    : [ "生命力+500;攻擊力+300;回復力+150", "5顆直排劍20%", "冷卻回合永久-4", "直排心符石掉落提升至25%" ],
        leader       : "WILL_SURVIVE",
        active       : [ "DESPERATE_ATTACK", "DESPERATE_PREPARE" ],
    },
// @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
};

function NewCharacter( id ){
    var characterObj = $.extend(true, {}, CHARACTERS_DATA[id]);
    return characterObj;
}

//==============================================================
// Color Letter Mapping
//==============================================================

var COLOR_LETTERS = [
    { 'w': '水', 'f': '火', 'p': '木', 'l': '光', 'd': '暗', 'h': '心', '_': '無' },
    { 'w': '浪濤', 'f': '熾燄', 'p': '藤木', 'l': '流螢', 'd': '幽冥', 'h': '心', '_': '無' },
    { 'w': '水', 'f': '焰', 'p': '森', 'l': '光', 'd': '魅', 'h': '心', '_': '無' },
    { 'w': '浪濤', 'f': '熾燄', 'p': '藤木', 'l': '玄光', 'd': '幽冥', 'h': '護心', '_': '無' },
    { 'w': '海', 'f': '炎', 'p': '森', 'l': '聖', 'd': '邪', 'h': '心', '_': '無' },
    { 'w': '波濤', 'f': '火烈', 'p': '枯朽', 'l': '天雷', 'd': '背叛', 'h': '心', '_': '無'},
    { 'w': '漩渦', 'f': '焰芒', 'p': '呼嘯', 'l': '聖焰', 'd': '吞噬', 'h': '心', '_': '無'},
];

var COLOR_EXCLUSIVE = {
    'w': 'f', 'f': 'p', 'p': 'w', 'l': 'd', 'd': 'l', 'h': 'w', '_': 'w'
};
var COLOR_ANTI_EXCLUSIVE = {
    'w': 'p', 'f': 'w', 'p': 'f', 'l': 'd', 'd': 'l', 'h': 'w', '_': 'w'
};

var MAIN_STATE_ENUM = {
    READY          : 0,
    MOVING         : 1,
    COUNT_GROUP    : 2,
    COUNT_ATK      : 3,
    BATTLE_INFO    : 4,
    TIME_TO_MOVE   : 5,
    REVIEW         : 6,
    CREATE         : 7,
}
var PLAY_TYPE_ENUM = {
    DRAG  : 0,
    FREE  : 1,
};
var GAME_MODE_ENUM = {
    NORMAL : 0,
    REPEAT : 1,
};


//==============================================================
// Attack Recover 
//==============================================================

var BASIC_ATTACK = {
    base   : 0,
    color  : "_",
    damage : 0,
    factor : 0,
    goal   : "single",
    place  : -1,
    strong : false,
    style  : "NONE",
    type   : "NONE",
    target : [],
    log    : "",
    work   : "init",
};
var BASIC_RECOVER = {
    base   : 0,
    color  : "_",
    factor : 0,
    place  : -1,
    style  : "NONE",
    type   : "NONE",
    log    : "",
    work   : "init",
};
var BASIC_INJURE = {
    enemy  : 0,
    label  : "",
    damage : 0,
    color  : "_",
    work   : "init",
};

function makeNewAttack(){
    var attack = $.extend(true, {}, BASIC_ATTACK);
    return attack;
}
function makeNewRecover(){    
    var recover = $.extend(true, {}, BASIC_RECOVER);
    return recover;
}
function makeNewInjure(){    
    var injure = $.extend(true, {}, BASIC_INJURE);
    return injure;
}